//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Realization.Database.Generation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopName
    {
        public ShopName()
        {
            this.Shops = new HashSet<Shop>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Shop> Shops { get; set; }
    }
}
