//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Realization.Database.Generation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.ShopProducts = new HashSet<ShopProduct>();
        }
    
        public int Id { get; set; }
        public int ShopNameId { get; set; }
        public string Address { get; set; }
        public string Shedule { get; set; }
    
        public virtual ShopName ShopName { get; set; }
        public virtual ICollection<ShopProduct> ShopProducts { get; set; }
    }
}
